name: ScriptableMC-Engine-JS
description: 'Run JavaScript/TypeScript plugins for Bukkit/Spigot/Paper Minecraft 1.15'
version: '1.3.0'
api-version: '1.13'
author: AStorks
main: com.pixlfox.scriptablemc.SMCJavaScriptEngineMain
softdepend: [PlaceholderAPI, CommandAPI]